#!/bin/bash
source pubkey.txt
args=("$@")
seed_ip=`getent hosts zero.kolo.supernet.org | awk '{ print $1 }'`
komodo_binary='./komodod'
delay=20

function komodo_asset ()
{
    if [ $[RANDOM % 10] == 1 ]
    then
        gen=" -gen"
    else
        gen=""
    fi

    if [ -n "$2" ]
    then
        supply=" -ac_supply=$2"
    else
        supply=" "
    fi

    $komodo_binary -pubkey=$pubkey -ac_name=$1 $supply -addnode=$seed_ip $gen $args &
    sleep $delay
}

#set -x
ASSETCHAINS_DATA="./assetchains_data"
IFS='
'
for ASSET in `cat ${ASSETCHAINS_DATA}`;do
    AC_NAME=`echo ${ASSET} | awk -F " " '{print $1}'`
    SUPPLY=`echo ${ASSET} | awk -F " " '{print $2}'`
    komodo_asset ${AC_NAME} ${SUPPLY}
done
